#!/bin/bash

FILENAME="$(fzf)"

case "$FILENAME" in
  *mkv | *mp4 | *mp3 | *ts)
    mpv "$FILENAME"
    ;;
  *tex | *c | *h | *java)
    vim "$FILENAME"
    ;;
  *pdf)
    zathura --fork "$FILENAME"
    ;;
esac

