#!/bin/bash

## @file
# Runs the file selected with fzf. The file is ran by an app chosen
# based on the file extension.
#
# @author Anh Dinh Trong <ad438310@students.mimuw.edu.pl>
# @date 2022
#

FILENAME="$(fzf)"

case "$FILENAME" in
  *mkv | *mp4 | *mp3 | *ts)
    mpv "$FILENAME"
    ;;
  *tex | *c | *h | *java)
    vim "$FILENAME"
    ;;
  *pdf)
    zathura --fork "$FILENAME"
    ;; # Feel free to add your functionality.
esac

