#!/bin/bash

FILENAME="$(find ~ -not -path "*/.*" | fzf)"
cd "$(dirname "$FILENAME")"

case "$FILENAME" in
  *mkv | *mp4 | *mp3 | *ts)
    mpv "$FILENAME"
    ;;
  *tex | *c | *h | *java)
    vim "$FILENAME"
    ;;
  *pdf)
    zathura --fork "$FILENAME"
    ;;
esac
