#!/bin/bash

## @file
# Pulls from all branches including master.
#
# @author Anh Dinh Trong <ad438310@students.mimuw.edu.pl>
# @date 2022
#

THEMES=(alicia beatrice maria master)
REPO="$HOME/Build/dwm"

if [[ $(pwd) != $REPO ]]; then
  echo "Please move to the repository directory."
fi

for tm in ${THEMES[@]}; do
  echo "Pulling $tm..."
  git checkout $tm
  git pull 
  echo "Done!"; sleep 1
done
