#!/bin/bash

## @file
# Commits and pushes a pushed master to the all themes.
#
# $1 - current theme.
#
# @author Anh Dinh Trong <ad438310@students.mimuw.edu.pl>
# @date 2022
#

THEMES=(alicia beatrice maria)
REPO="$HOME/Build/dwm"

current="$1"

reg1="^[[:alnum:]]+$"
reg2="\b$theme\b"
if [[ ! $theme =~ $reg1 || ! ${THEMES[@]} =~ $reg2 ]]; then
  echo "There's no such theme."
  exit 1
fi

if [[ $(pwd) != $REPO ]]; then
  echo "Please move to the repository directory."
fi

echo "Pushing master..."
git push
echo "Done!"; sleep 1

for tm in ${THEMES[@]}; do
  echo "Pushing $tm..."
  git checkout $tm
  git cherry-pick master
  git push
  echo "Done!"; sleep 1
done

git checkout current
